# Generated by Django 5.0.6 on 2024-06-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="captcha",),
        migrations.RemoveField(model_name="comment", name="home_page",),
        migrations.AddField(
            model_name="comment",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="comment_files/"),
        ),
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="comment_images/"),
        ),
    ]
