# Generated by Django 5.0.6 on 2024-06-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_remove_comment_captcha_remove_comment_home_page_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="file",),
    ]
